name: 'Build and push Docker Action'
description: 'Build and push a docker image'
inputs:
  user:
    default: ''
  pass:
    default: ''
  registry:
    default: 'registry-1.docker.io'
  path:
    required: true
  name:
    required: true
  build_args:
    default: ''
  tags:
    default: 'latest'
  date_tag:
    default: false
  commit_tag:
    default: false
  force_pull:
    default: false
  no_cache:
    default: true
  no_push:
    default: false
  tmp_tag:
    default: 'tmp-build-tag:latest'
  only_on_repo:
    default: ''
  push_on_repo:
    default: ''
  buildkit:
    default: true
runs:
  using: 'docker'
  image: 'Dockerfile'
